function ev_files = review_ev_files(EvApp, datafilelist)
%review_ev_files
%
% Give the user a list of the Echoview worksheets and open them in echoview
% as requested.
%
% This function saves and closes the worksheets when the user selects the
% next one.
       
    EvFile = [];
    
    % layout variables
    bbase = 0.02;
    bheight = 0.06;
    bwidth = 0.15;
    bstep = 0.2;
    left = 0.025;
    
    % build the GUI
    fig = figure( ...
        'CloseRequestFcn',  @done);
    
    main_panel = uipanel(...
        'Parent',       fig, ...
        'BorderType',   'none');
    
    list = uicontrol(main_panel, ...
        'Style',        'listbox', ...
        'TooltipString', 'Select a worksheet and press review', ...
        'String',       datafilelist, ...
        'Value',        1, ...
        'Units',        'normalized', ...
        'Position',     [0 0.1 1 0.9 ]);
    
    uicontrol(main_panel, ...
        'Style',        'pushbutton', ...
        'TooltipString', 'Review the selected worksheet', ...
        'String',       'Review', ...
        'Units',        'normalized', ...
        'Position',     [left bbase bwidth bheight ], ...
        'Callback',     @review);
    
    left = left + bstep;
    uicontrol(main_panel, ...
        'Style',        'pushbutton', ...
        'TooltipString', 'Review the next worksheet', ...
        'String',       'Next', ...
        'Units',        'normalized', ...
        'Position',     [left bbase bwidth bheight ], ...
        'Callback',     @next);
    
    left = left + bstep;
    uicontrol(main_panel, ...
        'Style',        'pushbutton', ...
        'TooltipString', 'Finish the review and continue processing', ...
        'String',       'Done', ...
        'Units',        'normalized', ...
        'Position',     [left bbase bwidth bheight ], ...
        'Callback',     @done);
    
    left = left + bstep;
    uicontrol(main_panel, ...
        'Style',        'pushbutton', ...
        'TooltipString', 'Finish the review and select a subset of EV files for processing', ...
        'String',       'Select', ...
        'Units',        'normalized', ...
        'Position',     [left bbase bwidth bheight ], ...
        'Callback',     @select);
    
    left = left + bstep;
    uicontrol(main_panel, ...
        'Style',        'pushbutton', ...
        'TooltipString', 'Finish the review and abort further processing', ...
        'String',       'Cancel', ...
        'Units',        'normalized', ...
        'Position',     [left bbase bwidth bheight ], ...
        'Callback',     @cancel);
    
    waitfor(fig)
    
    
    function closeEv(~, ~)
        % Close any open worksheets
        if ~isempty(EvFile)
            try
                EvFile.Save;
                EvFile.Close;
            catch e
                fprintf('Unable to close worksheet: %s\n', e.message);
            end
            EvFile = [];
        end
    end

    function review(~, ~)
        % Review button pressed, close the open worksheet (if any) and open
        % the selected worksheet.
        closeEv();
        
        filename = datafilelist{get(list, 'Value')};
        EvFile = EvApp.OpenFile(filename);
    end

    function next(~, ~)
        % Next button pressed, If we are at the end of the list call done
        % else review the next worksheet on the list.
        
        curr = get(list, 'Value');
        if curr < length(datafilelist)
            set(list, 'Value', curr +1);
            review();
        else
            done();
        end
    end

    function done(~, ~)
        % Done button pressed. Close any worksheets and the figure
        closeEv();
        ev_files = datafilelist;
        delete(fig);
    end

    function cancel(~, ~)
        % Cancel button pressed. Close any worksheets and the figure
        closeEv();
        ev_files = {};
        delete(fig);
    end

    function select(~, ~)
        closeEv();
        set(list, ...
            'Min',      0, ...
            'Max',      length(datafilelist), ...
            'Value',    1:length(datafilelist));
        
        uicontrol(get(list, 'Parent'), ...
            'Style',        'pushbutton', ...
            'TooltipString', 'Finish the selection', ...
            'String',       'OK', ...
            'Units',        'normalized', ...
            'Position',     [0.025 0.02 0.95 0.06 ], ...
            'Callback',     @selected);
    end
        
    function selected(~,~)
        ev_files = datafilelist(get(list, 'Value'));
        delete(fig);
    end
end
        
    
    
    
    
